### ISSUE TITLE
Persona: tipos de dato, etiquetas

### ISSUE THREAD

**Issue by joseanrey** [masiaventura/masiaventura#2]
Hola, pongo por aquí algunas cuestiones que he visto en el formulario de añadir persona nueva.

"Districto" en lugar de "Distrito"
"Mediación" en lugar de "Medicación"
"Trabajador social" en lugar de "Trabajador/a Social"

"Caso en ETMF" de tipo cadena de texto en lugar de booleano
"Tiene expediente en CAI" en lugar de "Caso en CAI"
"Caso en CAF" de tipo cadena de texto en lugar de booleano

Gracias
Saludos

**Comment by mariogarcia** [comment]
Gracias, lo corrijo para la proxima version

**Comment by mariogarcia** [comment]
Vale veo algunos campos con errores en los literales, pero otros son cambios en el modelo de datos que requeriran migracion. Voy a dejar en esta issue solo los tipos y dejo los cambios del modelo en otra issue.
