### ISSUE TITLE
Crear proceso, autorizaciones: Error 500

### ISSUE THREAD

**Issue by joseanrey** [masiaventura/masiaventura#6]
No se pueden crear procesos asociados a personas y proyectos ni subir autorizaciones. Error 500.

**Comment by mariogarcia** [comment]
Me puedes pasar un pantallazo con el error de consola o de la pantalla de error que sale ?

**Comment by joseanrey** [comment]
Si! Te copio log de docker al intentar crear proceso para id 357: Error500.

https://pastebin.com/K3B4BX3S

**Comment by mariogarcia** [comment]
Lo estoy probando en local con una base de datos en memoria y funciona bien. Estais usando PostgreSQL ? Es por saber contra que probar para hacer la prueba buena.

**Comment by joseanrey** [comment]
Si, con el mismo archivo de configuración *.yaml del repositorio, únicamente añadí POSTGRES_PASSWORD con una contraseña para la base de datos.

**Comment by mariogarcia** [comment]
Ya se lo que esta pasando. La forma en la que esta programado, supone que la conexión a base de datos es de **autocommit**, es decir que cuando le dices al ORM que salve este salva y si la base de datos tiene configurado autocommit, lo salva "de verdad" (por eso funciona en una base de datos en memoria), pero si la base de datos por defecto no lo tiene configurado asi (como PostgreSQL), pues hay que ser explicito haciéndolo.

Vale pues voy a ello.
