### ISSUE TITLE
Edad Persona

### ISSUE THREAD

**Issue by joseanrey** [masiaventura/masiaventura#7]
El dato calculado de la "Edad" de la persona únicamente se muestra en el listado de Personas. Estaría fetén si se mostrara en la parte destacada del detalle de la ficha.

**Comment by mariogarcia** [comment]
Lo he agregado junto a la fecha de nacimiento. De un vistazo puedes ver su edad.

![person_detail_age](https://user-images.githubusercontent.com/1414131/79159528-8c641a80-7dd8-11ea-8381-825a551b69b5.png)
