### ISSUE TITLE
Fecha de Baja

### ISSUE THREAD

**Issue by joseanrey** [masiaventura/masiaventura#8]
No aparece la fecha de baja en el formulario "Persona".

**Comment by mariogarcia** [comment]
@joseanrey  estoy implementando el botón de hacer inactivo (dar de baja) a una persona. Aunque supongo que hay una serie de cosas que habría que tener en cuenta y poner en común cuando se da de baja:

- Se mantiene el acceso de solo lectura
- No se puede editar el detalle
- No se pueden editar los procesos
- No se pueden editar las autorizaciones
- Solo el administrador puede activarlo otra vez desde el detalle de la persona desactivada

Ademas cuando se da de baja a una persona se debe mostrar un modal que haga confirmar la acción al usuario, y de manera opcional dar una razón para la baja.

![baja](https://user-images.githubusercontent.com/1414131/79166634-e5867b00-7de5-11ea-8a59-1dec15016cb6.png)

Se mostrara la fecha de la baja y el estado inactivo en el detalle del usuario

![baja_detail](https://user-images.githubusercontent.com/1414131/79166770-2da59d80-7de6-11ea-9ca4-78fae230fbeb.png)

... y en el listado de personas

![baja_list](https://user-images.githubusercontent.com/1414131/79166831-4ca42f80-7de6-11ea-9ada-973980f3368c.png)

**Comment by mariogarcia** [comment]
Incluido en version 0.2.0
